apiVersion: apps/v1
kind: Deployment
metadata:
  name: mt3gateway-step2-dep
  namespace: {{ .Values.namespace }}
  labels:
    app: mt3gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: mt3gateway-step2-pod
  template:
    metadata:
      annotations:
        dapr.io/app-id: "step2"
{{ include  "gatewaydapr" . | indent 8 }}
{{ include  "gatewayconfig" . | indent 8 }}
      labels:
        tier: mt3gateway-step2-pod
        action: calculation
        color: lime
    spec:
      nodeSelector:
        kubernetes.io/os: linux       
      containers:
      - name: mt3gateway-step2
        {{ if eq .Values.platform "dotnet" }}
        image: {{ .Values.repo }}/mt3gateway-step2:{{ .Values.tags.mt3gatewaystep2 }}
        {{ else }}
        image: {{ .Values.repo }}/mt3gateway-step2-nodejs:{{ .Values.tags.mt3gatewaystep2nodejs }}
        {{ end}}
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: mt3gateway-config        
        env:
        - name: CalcStepVariable
          value: "9"
