apiVersion: apps/v1
kind: Deployment
metadata:
  name: mt3gateway-step5-dep
  namespace: {{ .Values.namespace }}
  labels:
    app: mt3gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: mt3gateway-step5-pod
  template:
    metadata:
      annotations:
        dapr.io/app-id: "step5"
{{ include  "gatewaydapr" . | indent 8 }}
{{ include  "gatewayconfig" . | indent 8 }}
      labels:
        tier: mt3gateway-step5-pod
        action: calculation
        color: lime
    spec:
      nodeSelector:
        kubernetes.io/os: linux       
      containers:
      - name: mt3gateway-step5
        image: {{ .Values.repo }}/mt3gateway-step5:{{ .Values.tags.mt3gatewaystep5 }}
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: mt3gateway-config        
